version: '3'
services:
  # RabbitMQ Docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - esalonljepotenet

#mssql docker
  esalonljepote-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=st123W!a
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - esalonljepotenet

  esalonljepote-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=esalonljepote-sql,1433;Database=eSalonLjepote;User=sa;Password=st123W!a;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=testadna.98@gmail.com
      - SMTP_PASSWORD=pncplaqmwefauont
    ports:
      - 7071:7071
    networks:
      - esalonljepotenet
    links:
      - esalonljepote-sql
    depends_on:
      - esalonljepote-sql
      - rabbitmq

        # RabbitMQ Service Docker
  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eSalonLjepote.Subscriber/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=testadna.98@gmail.com
      - SMTP_PASSWORD=pncplaqmwefauont
    depends_on:
      - rabbitmq
    networks:
      - esalonljepotenet
      
networks:
  esalonljepotenet:
    driver: bridge     